# Generated by Django 4.1.3 on 2023-04-04 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
